# Generated by Django 4.0.2 on 2022-02-24 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name', max_length=20)),
                ('last_name', models.CharField(help_text='last name', max_length=20)),
                ('email', models.EmailField(help_text='email address', max_length=254)),
                ('phone', models.IntegerField(help_text='phone number', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(help_text='story')),
                ('photo', models.FileField(help_text='file example photo or video', upload_to='')),
                ('story_date', models.DateField(verbose_name='data story was recorded')),
                ('type', models.CharField(help_text='type of story', max_length=50)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stories.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='comment given to the story')),
                ('comment_date', models.DateField(verbose_name='date comment was given')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
            ],
        ),
    ]
