# Generated by Django 4.0.2 on 2022-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(help_text='phone number'),
        ),
    ]
